### ISSUE TITLE
Error: Received RST_STREAM with error code 2

### ISSUE THREAD

**Issue by redstone99** [googleapis/nodejs-datastore#1134]
#### Environment details

  - OS: Debian 5.10.179-3 (2023-07-27) (running on google compute)
  - Node.js version: v18.17.0
  - npm version: 9.6.7
  - `@google-cloud/datastore` version: 7.5.1
  - `@grpc/grpc-js` version: 1.8.21

#### Steps to reproduce

It happens intermittently, just started happening a few times a day on 7/31/2023. Hadn't seen it in a few years before that.  It looks like a similar bug has affected other google node modules. Perhaps the solution is similar?
Sample stack trace, resulting from doing a `lookup` of a key on the datastore from within a transaction:

```
8/4 0:16:1.457: (/opt/app/client-datastore.js:162:6):  'Lookup error: ' Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
    at callErrorFromStatus (/opt/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/opt/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/opt/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/opt/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /opt/app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/opt/app/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.<anonymous> (/opt/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /opt/app/node_modules/@google-cloud/datastore/build/src/v1/datastore_client.js:225:29
    at /opt/app/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat (/opt/app/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
    at /opt/app/node_modules/google-gax/build/src/normalCalls/retries.js:118:13
    at OngoingCall.call (/opt/app/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/opt/app/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /opt/app/node_modules/google-gax/build/src/createApiCall.js:84:30 {
  code: 13,
  details: 'Received RST_STREAM with code 2 (Internal server error)',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}

```

**Comment by danieljbruce** [comment]
I tried the following and see no issues:

```
// Imports the Google Cloud client library
const {Datastore} = require('@google-cloud/datastore');
// Creates a client
const datastore = new Datastore();

async function printEntities() {
  const key = datastore.key(['Company', 'Google']);
  const transaction = datastore.transaction();
  await transaction.run();
  const results = await transaction.get(key);
  console.log(results);
}
printEntities()
```

Please provide your script that fails here. Also try running the script with environment variables `GRPC_TRACE=all;GRPC_VERBOSITY=DEBUG` set and then paste the output here.

**Comment by redstone99** [comment]
Yeah, it was only intermittent and it stopped happening a week ago.  I haven't updated grpc or datastore, so I'm not sure what changed.  I guess we can close this.
