### ISSUE TITLE
ESM import crashes App Engine install/build process ("Cannot set property AggregateField of #<Object> which has only a getter")

### ISSUE THREAD

**Issue by rossjs** [googleapis/nodejs-datastore#1160]
My team just went through and upgraded our code to use ESM modules and this library is specifically crashing when deployed via App Engine. It works fine locally, but something about how to code is being built is crashing when App Engine installs this module.

Even if I don't actually use the library and just include `import { Datastore } from '@google-cloud/datastore'` in my code anywhere, I get the following error in my logs:

```
TypeError: Cannot set property AggregateField of #<Object> which has only a getter
    at Object.<anonymous> (/workspace/node_modules/@google-cloud/datastore/build/src/index.js:18:247)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/workspace/node_modules/@google-cloud/datastore/build/src/transaction.js:21:12)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
```

#### Environment details

  - OS: Ubuntu? (not sure what's under the hood for App Engine these days)
  - Node.js version: 20
  - npm version: 9?
  - `@google-cloud/datastore` version: 8.1.0

#### Steps to reproduce

  1. Create a new folder
  2. Create the files listed in [this gist](https://gist.github.com/rossjs/65ab1a091c46b80d3b7940ac3c9f9f9d)
  3. Update the `INSERT_YOUR_GCP_PROJECT` placeholder in package.json
  4. run `npm run deploy` (you may want to remove the `service` field from the app.yaml file to deploy to the default service if deploying to a project that doesn't currently use App Engine)
  5. in the GCP console, go to App Engine -> Services and then click on Logs (under the Diagnose column) for the service you just deployed
  6. Click the "Stream logs" button streaming the logs
  7. Go to the URL for your deployed service in a separate tab and then go back to the logs page to see the error (it may take a few minutes for the logs to start showing)

**Comment by danieljbruce** [comment]
We are having trouble reproducing the problem. Is there another other part of this setup that might be missing?

**Comment by rossjs** [comment]
Yeah... I'm seeing the same thing. I think this must have been some sort of weird caching issue with App Engine or something. Sorry about that!

Thanks for the quick response anyway.
