### ISSUE TITLE
Failing to retrieve default credentials logs several exceptions

### ISSUE THREAD

**Issue by johnviolano** [googleapis/nodejs-datastore#137]
When default credentials cannot be loaded, I am receiving 6 exceptions and seem to be only able to catch the first...

#### Environment details

  - OS: OSX
  - Node.js version: 10.6.0
  - npm version: 6.1.0
  - `@google-cloud/datastore` version: 1.4.1

#### Steps to reproduce

1. Clear your credentials
2. Create a Datastore and run a query on it.

`
const results = query.run()
.catch(err => {
    console.log("here");
});
`

2. Observe the output:

```
here
(node:19156) UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:248:31)
    at step (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at fulfilled (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whichwas not handled with .catch(). (rejection id: 3)
(node:19156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19156) UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:248:31)
    at step (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at fulfilled (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whichwas not handled with .catch(). (rejection id: 4)
(node:19156) UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:248:31)
    at step (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at fulfilled (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whichwas not handled with .catch(). (rejection id: 5)
(node:19156) UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:248:31)
    at step (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at fulfilled (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whichwas not handled with .catch(). (rejection id: 6)
(node:19156) UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:248:31)
    at step (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at fulfilled (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whichwas not handled with .catch(). (rejection id: 7)
(node:19156) UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:248:31)
    at step (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at fulfilled (/Users/foo/Development/project/server/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

Could this be similar or related to this issue?
[https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2413](url)

Caveat:
I'm new to Nodejs and google cloud :)

**Comment by stephenplusplus** [comment]
Sorry :( Here is the issue that should fix this: https://github.com/googleapis/gax-nodejs/issues/121.
