### ISSUE TITLE
Getting RESOURCE_EXHAUSTED message when trying to load entities from DS emulator

### ISSUE THREAD

**Issue by glenpike** [googleapis/nodejs-datastore#165]
#### Environment details

  - OS: OSX El Capitan (10.11.6) Using about 12GB / 16GB memory
  - Node.js version: v8.11.2
  - npm version: 6.3.0
  - `@google-cloud/datastore` version:
```
├─┬ @google-cloud/datastore@1.4.1
│ ├─┬ @google-cloud/common@0.19.2
```

Using DataStore via: gstore-node@4.2.4

#### Steps to reproduce

  1. Asking for a list of upto 1000 entities from the DB:

```
Model.all = (querySettings, cursor = EMPTY_CURSOR) => async ctx => new Promise((resolve) => {
    const qSet = querySettings || {};
    if (!qSet.limit) qSet.limit = 1000;
    if (!qSet.format) qSet.format = 'ENTITY';
    if (cursor !== EMPTY_CURSOR) qSet.start = cursor;
    qSet.namespace = ctx.namespace;
    Model
      .list(qSet)
      .then(async (result) => {
        const { entities: results, nextPageCursor } = result;
        if (results && results.length > 0) {
          if ((nextPageCursor && nextPageCursor !== EMPTY_CURSOR) &&
                        (!qSet.limit || (qSet.limit && results.length < qSet.limit))) {
            const {
              results: subResults,
            } = await Model.all(querySettings, nextPageCursor);
            Object.assign(results, subResults);
          }
        }
        resolve({
          results,
          cursor: nextPageCursor,
        });
      })
      .catch(e => parseError(e));
  });
```

There are only 66 entities, but expect some of these have grown quite large.

Does not happen if I query the data on 'production' [datastore](https://console.cloud.google.com/datastore/entities/query/gql) with 'SELECT * FROM Model' - this returns a page of results.

Happens if I try to inspect the entity type using the [google-cloud-gui](https://github.com/gabiaxel/google-cloud-gui) datastore browser: 
```
    at buildError (/Users/glen/.nvm/versions/node/v8.11.2/lib/node_modules/google-cloud-gui/node_modules/server/error/index.js:2:17)
    at ErrorInstance (/Users/glen/.nvm/versions/node/v8.11.2/lib/node_modules/google-cloud-gui/node_modules/server/error/index.js:19:12)
    at AsyncFunction.handler.error.ctx [as error] (/Users/glen/.nvm/versions/node/v8.11.2/lib/node_modules/google-cloud-gui/node_modules/server/plugins/final/index.js:23:19)
    at Object.middle (/Users/glen/.nvm/versions/node/v8.11.2/lib/node_modules/google-cloud-gui/node_modules/server/src/join/index.js:36:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  status: 500,
  namespace: '/plugin/final/',
  code: '/plugin/final/unhandled',
  id: 'plugin-final-unhandled' }
[Thu Aug 09 2018 17:13:20 GMT+0100 (BST)] ERROR { Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (4266077 vs. 4194304)
    at Object.exports.createStatusError (/Users/glen/.nvm/versions/node/v8.11.2/lib/node_modules/google-cloud-gui/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/Users/glen/.nvm/versions/node/v8.11.2/lib/node_modules/google-cloud-gui/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/Users/glen/.nvm/versions/node/v8.11.2/lib/node_modules/google-cloud-gui/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/glen/.nvm/versions/node/v8.11.2/lib/node_modules/google-cloud-gui/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/Users/glen/.nvm/versions/node/v8.11.2/lib/node_modules/google-cloud-gui/node_modules/grpc/src/client_interceptors.js:841:24)
  code: 8,
  metadata: Metadata { _internal_repr: {} },
  details: 'Received message larger than max (4266077 vs. 4194304)',
  note: 'Exception occurred in retry method that was not classified as transient' }
```

Suspect this may be 'lower down' or a config for the grpc message size after looking at other bugs, e.g. , but don't know if this is on the server or client side, e.g. emulator or this repo?

Thanks very much for listening.

**Comment by stephenplusplus** [comment]
Hello! Judging from the error, I believe you're right-- you need to set a low-level gRPC setting. If you were using @google-cloud/datastore directly, it would look like:

```js
const Datastore = require('@google-cloud/datastore')
const datastore = new Datastore({
  'grpc.max_send_message_length': -1, // unlimited
  'grpc.max_receive_message_length': -1 // unlimited
})
```

I'm not sure how that will look using the other libraries. Hopefully this is enough information to go on-- if you get stuck, or it still doesn't work, let me know!

**Comment by glenpike** [comment]
Cool, nice.  Thanks for the information.  I'll check to see if gstore-node can do that and keep an eye on the other bug you've 'created' to try and handle this :+1:

**Comment by glenpike** [comment]
Hi, @stephenplusplus  thanks for the info, we managed to fix this in our code - gstore-node is passed an instance of @google-cloud/datastore when it's created, so the above 'patch' works.  👍
e.g.
```
const gstore = require('gstore-node')();

 const dsConfig = {
  projectId: GOOGLE_PROJECT_ID,
  'grpc.max_send_message_length': -1, // unlimited
  'grpc.max_receive_message_length': -1, // unlimited
  apiEndpoint: 'localhost:8011',
};
const datastore = require('@google-cloud/datastore')(dsConfig);
gstore.connect(datastore);
```

**Comment by stephenplusplus** [comment]
Thank you very much for coming back and showing how to do it!

**Comment by chadbr** [comment]
This is working for me -- should it be the default? @stephenplusplus

**Comment by stephenplusplus** [comment]
I think so, but for all APIs. I opened that question here, where it would be a single merge to change it API-wide: https://github.com/googleapis/gax-nodejs/issues/287
