### ISSUE TITLE
System tests failing on master

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-datastore#357]
At some point over the last few days, the system tests started to fail on master :(

```
Datastore {
  KEY: Symbol(KEY),
  MORE_RESULTS_AFTER_CURSOR: 'MORE_RESULTS_AFTER_CURSOR',
  MORE_RESULTS_AFTER_LIMIT: 'MORE_RESULTS_AFTER_LIMIT',
  NO_MORE_RESULTS: 'NO_MORE_RESULTS',
  DatastoreRequest: [Function: DatastoreRequest],
  Query: [Function: Query],
  Transaction: [Function: Transaction],
  clients_: Map {},
  datastore: [Circular],
  namespace: undefined,
  projectId: '{{projectId}}',
  defaultBaseUrl_: 'datastore.googleapis.com',
  baseUrl_: 'datastore.googleapis.com',
  options:
   { libName: 'gccl',
     libVersion: '3.1.2',
     scopes:
      [ 'https://www.googleapis.com/auth/cloud-platform',
        'https://www.googleapis.com/auth/datastore' ],
     servicePath: 'datastore.googleapis.com',
     port: 443,
     projectId: undefined },
  auth:
   GoogleAuth {
     checkIsGCE: undefined,
     jsonContent: null,
     cachedCredential: null,
     _cachedProjectId: null,
     keyFilename: undefined,
     scopes:
      [ 'https://www.googleapis.com/auth/cloud-platform',
        'https://www.googleapis.com/auth/datastore' ],
     clientOptions: undefined } }
    ✓ should be able to use the d.ts (15971ms)
  29 passing (28s)
  8 failing
  1) Datastore
       create, retrieve and delete
         should excludeFromIndexes correctly:
      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped
  {
-   [Symbol(KEY)]: Key {
-     kind: 'Post',
-     name: 'post1',
-     namespace: undefined,
-     path: [Getter]
-   },
    longString: '.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................',
...
    notMetadata: true
  }
      + expected - actual
      at Object.<anonymous> (system-test/datastore.ts:124:14)
      at Generator.next (<anonymous>)
      at fulfilled (build/system-test/datastore.js:19:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  2) Datastore
       create, retrieve and delete
         should save/get/delete with a key name:
      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped
  {
-   [Symbol(KEY)]: Key {
-     kind: 'Post',
-     name: 'post1',
-     namespace: undefined,
-     path: [Getter]
-   },
    author: 'Silvano',
...
    wordCount: 400
  }
      + expected - actual
      at Object.<anonymous> (system-test/datastore.ts:133:14)
      at Generator.next (<anonymous>)
      at fulfilled (build/system-test/datastore.js:19:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  3) Datastore
       create, retrieve and delete
         should save/get/delete with a numeric key id:
      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped
  {
-   [Symbol(KEY)]: Key {
-     id: '123456789',
-     kind: 'Post',
-     namespace: undefined,
-     path: [Getter]
-   },
    author: 'Silvano',
...
    wordCount: 400
  }
      + expected - actual
      at Object.<anonymous> (system-test/datastore.ts:142:14)
      at Generator.next (<anonymous>)
      at fulfilled (build/system-test/datastore.js:19:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  4) Datastore
       create, retrieve and delete
         should save/get/delete a buffer:
      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped
  {
-   [Symbol(KEY)]: Key {
-     id: '5718556666757120',
-     kind: 'Post',
-     namespace: undefined,
-     path: [Getter]
-   },
    buf: Buffer [Uint8Array] [
...
    ]
  }
      + expected - actual
      at Object.<anonymous> (system-test/datastore.ts:155:14)
      at Generator.next (<anonymous>)
      at fulfilled (build/system-test/datastore.js:19:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  5) Datastore
       create, retrieve and delete
         should save/get/delete with a generated key id:
      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped
  {
-   [Symbol(KEY)]: Key {
-     id: '5655872894140416',
-     kind: 'Post',
-     namespace: undefined,
-     path: [Getter]
-   },
    author: 'Silvano',
...
    wordCount: 400
  }
      + expected - actual
      at Object.<anonymous> (system-test/datastore.ts:167:14)
      at Generator.next (<anonymous>)
      at fulfilled (build/system-test/datastore.js:19:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  6) Datastore
       create, retrieve and delete
         should fail explicitly set second insert on save:
      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped
  {
-   [Symbol(KEY)]: Key {
-     id: '5178421042741248',
-     kind: 'Post',
-     namespace: undefined,
-     path: [Getter]
-   },
    author: 'Silvano',
...
    wordCount: 400
  }
      + expected - actual
      at Object.<anonymous> (system-test/datastore.ts:210:14)
      at Generator.next (<anonymous>)
      at fulfilled (build/system-test/datastore.js:19:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  7) Datastore
       querying the datastore
         should select projections:
      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped
  {
-   [Symbol(KEY)]: Key {
-     kind: 'Character',
-     name: 'Arya',
-     namespace: undefined,
-     parent: Key {
-       kind: 'Character',
-       name: 'Eddard',
-       namespace: undefined,
-       parent: Key {
-         kind: 'Character',
-         name: 'Rickard',
-         namespace: undefined,
-         parent: Key {
-           kind: 'Book',
-           name: 'GoT',
-           namespace: undefined,
-           path: [Getter]
-         },
-         path: [Getter]
-       },
...
...
      + expected - actual
      at Object.<anonymous> (system-test/datastore.ts:507:14)
      at Generator.next (<anonymous>)
      at fulfilled (build/system-test/datastore.js:19:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  8) Datastore
       transactions
         should run in a transaction:
      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual
  {
-   [Symbol(KEY)]: Key {
-     kind: 'Company',
-     name: 'Google',
-     namespace: undefined,
-     path: [Getter]
-   },
    url: 'www.google.com'
  }
      + expected - actual
      at Object.<anonymous> (system-test/datastore.ts:580:14)
      at Generator.next (<anonymous>)
      at fulfilled (build/system-test/datastore.js:19:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

https://source.cloud.google.com/results/invocations/9370bfb1-a6bc-4f28-b9ac-7aa61798bb89/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-datastore%2Fnode10%2Fsystem-test/log

**Comment by stephenplusplus** [comment]
Are links available for the failed builds?

**Comment by JustinBeckwith** [comment]
https://github.com/googleapis/nodejs-datastore/pull/358
