### ISSUE TITLE
IPv6 Emulator Addresses not functioning

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-datastore#502]
The Datastore emulator supports-- and automatically use sometimes-- IPv6 addresses (https://cloud.google.com/sdk/gcloud/reference/beta/emulators/datastore/start). Our code has only been parsing input such as "localhost:8081", which is still the default emulator address format. However, if you start a second emulator, or just define the address yourself, it can be IPv6.

![image](https://user-images.githubusercontent.com/723048/65457786-58b0ab80-de1a-11e9-837b-74a01994165e.png)

So, this is a two part issue.

1) Our code needs to figure out how to handle these addresses. This will definitely involve changes to our code, and possibly to the generated client code or gax as well. That code automatically concatenates `servicePath` and `port`, but IPv6 is a bit different. We might be able to get creative with parsing the IPv6 to work around that, e.g. `options.servicePath = '[::1:8244]'` and `options.port = ??`.

2) I can't seem to get gRPC to send requests to the IPv6 address. Here are the settings our client passes and then the response.

```js
{ libName: 'gccl',
  libVersion: '4.3.0',
  scopes:
   [ 'https://www.googleapis.com/auth/cloud-platform',
     'https://www.googleapis.com/auth/datastore' ],
  servicePath: '[::1:8244]',
  port: 443,
  projectId: undefined }
{ Error: Deadline exceeded
    at Http2CallStream.call.on (/Users/stephen/dev/nodejs-datastore/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
    at Http2CallStream.emit (events.js:194:15)
    at process.nextTick (/Users/stephen/dev/nodejs-datastore/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 4,
  details: 'Deadline exceeded',
  metadata: Metadata { options: undefined, internalRepr: Map {} } }
```

The emulator readout doesn't change, so it's not being hit.

- Is there a default emulator port for these addresses?
- Can gRPC handle directly pinging IPv6 addresses?
- Is there a strict format we should be following?
  - Do we use `http://`?
  - Does the IP have to be wrapped within brackets?
  - Is a specific port required?

I've tried all of the combinations I can think of, and it's either "Invalid URL: http://::1:8244" or a Deadline Exceeded error.

**Comment by stephenplusplus** [comment]
@bcoe @JustinBeckwith any ideas where to turn for halp?

**Comment by murgatroid99** [comment]
The grpc libraries can handle IPv6 addresses. I think the IP address you passed there is not the one you intended. The localhost address is `::1`, also written as `[::1]`. The address `[::1:8244]` is an entirely different address, and I'm not even sure it's valid. If you want localhost with port 8244, the format is `[::1]:8244`. But if you're doing that, you probably shouldn't also pass `port: 443`, which appears to be conflicting

However, all of this should be unnecessary. `localhost` should resolve to both the IPv4 and IPv6 addresses, and grpc should automatically connect to whichever one has a running service.

In both cases, an important caveat is that grpc-js cannot handle IPv6 addresses at all on Node versions below 12.6 as a result of nodejs/node#28216.

`http(s)://` should be omitted from addresses passed to grpc. If you want to specify that it is a dns address, prefix it with `dns://`.

**Comment by murgatroid99** [comment]
This `servicePath` and `port` setup is not gRPC's interface. The gRPC library accepts a single string that describes both the host and port. Some intermediate library is merging those two pieces of information to pass to gRPC, and that intermediate library is probably not sufficiently aware of IPv6 to enclose the `servicePath` in square brackets when that `servicePath` is an IPv6 address (but not otherwise).

**Comment by crwilcox** [comment]
We should add support to use IPv6 emulator, but I am not sure this is a bug. Relabeling.

**Comment by wlinna** [comment]
For me the emulator generates this kind of address: `[::1]:8052` . If I understood correctly, this should be in correct format. And yet it doesn't work either, while non-IPv6 addresses work just fine.
