### ISSUE TITLE
Datastore not respecting excludeFromIndexes on string

### ISSUE THREAD

**Issue by tommaitland** [googleapis/nodejs-datastore#53]
I've been unable to get Datastore to respect the exclude indexes property. I've tried different formats, different exclusion rules and different encoding but I'm not able to get beyond the 1500 byte error.

## Steps to Reproduce

I'm sending the following entity:
```
[
  {
    "name": "created",
    "value": "2018-02-07T14:39:35.072Z",
    "excludeFromIndexes": false
  },
  {
    "name": "processed",
    "value": false,
    "excludeFromIndexes": false
  },
  {
    "name": "uuid",
    "value": "b7681110-0c14-11e8-8fd8-970f8118462f",
    "excludeFromIndexes": false
  },
  {
    "name": "source",
    "value": "47a818c0-0b2e-11e8-9e34-cf75453428ac",
    "excludeFromIndexes": false
  },
  {
    "name": "data",
    "value": "eyJ0eXBlIjoiZG9uYXRpb24uY3JlYXRlZCIsImFwcCI6InJhaXNlbHkiLCJzb3VyY2UiOiI0N2E4MThjMC0wYjJlLTExZTgtOWUzNC1jZjc1NDUzNDI4YWMiLCJkYXRhIjp7InV1aWQiOiJiMzgyZTdhMC0wYzE0LTExZTgtOTRlYy03MzIxNmQ4OGJiMjkiLCJ0eXBlIjoiT05MSU5FIiwibWV0aG9kIjoiQ1JFRElUX0NBUkQiLCJjdXJyZW5jeSI6IkFVRCIsIm1lc3NhZ2UiOiIiLCJhbm9ueW1vdXMiOmZhbHNlLCJhbW91bnQiOjQwMDAsImNyZWF0ZWRBdCI6IjIwMTgtMDItMDdUMTQ6Mzk6MjguNjQzWiIsIm1vZGUiOiJURVNUIiwicHVibGljIjp7InBob3RvX3VybCI6IiIsInRvdGFsIjoiNDEuODIiLCJkb25hdGlvbl9hbW91bnQiOiI0MC4wMCIsImZlZSI6IjEuODIiLCJjdXJyZW5jeV9zeW1ib2wiOiIkIn0sInN0YXR1cyI6Ik9LIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaWQiOjEyLCJjYXJkIjoiY2FyZF8xQnNzclZDNUt6RXpIUE5oVnhKYUJoYlciLCJjdXN0b21lciI6ImN1c19DSFJsT1lyNXdyZHhveiIsInByb2Nlc3NpbmciOiJPTkNFIiwiZmVlIjoxODIsInRvdGFsIjo0MTgyLCJwcml2YXRlIjpudWxsLCJyZXN1bHQiOnsiaWQiOiJjaF8xQnN1NUJDNUt6RXpIUE5oUjZVMFZuRVQiLCJvYmplY3QiOiJjaGFyZ2UiLCJhbW91bnQiOjQwMDAsImFtb3VudF9yZWZ1bmRlZCI6MCwiYXBwbGljYXRpb24iOiJjYV83VDJodUxTeGJBRGdYajBSVGZmb3VmT25wYjJwV0RkbSIsImFwcGxpY2F0aW9uX2ZlZSI6ImZlZV8xQnN1NUJDNUt6RXpIUE5oMW05Z0hUaHYiLCJiYWxhbmNlX3RyYW5zYWN0aW9uIjoidHhuXzFCc3U1QkM1S3pFekhQTmhwZlR3Y0tXRyIsImNhcHR1cmVkIjp0cnVlLCJjcmVhdGVkIjoxNTE4MDE0MzczLCJjdXJyZW5jeSI6ImF1ZCIsImN1c3RvbWVyIjoiY3VzX0NIUmxPWXI1d3JkeG96IiwiZGVzY3JpcHRpb24iOiJEb25hdGlvbiAoMTIpIG9mIEFVRDQxLjgyIGZyb20gVGVzdCBUZXN0ICgxNCkgdG8gSnVtcCBmb3IgQ2hhbmdlICgxKSBmb3IgSnVtcCBmb3IgQ2hhbmdlICgxKSIsImRlc3RpbmF0aW9uIjpudWxsLCJkaXNwdXRlIjpudWxsLCJmYWlsdXJlX2NvZGUiOm51bGwsImZhaWx1cmVfbWVzc2FnZSI6bnVsbCwiZnJhdWRfZGV0YWlscyI6e30sImludm9pY2UiOm51bGwsImxpdmVtb2RlIjpmYWxzZSwibWV0YWRhdGEiOnsiZmlyc3RfbmFtZSI6IlRlc3QiLCJsYXN0X25hbWUiOiJUZXN0IiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiY2FtcGFpZ24iOiJtb2NrLWc1MHF0MWo4IiwicHJvZmlsZSI6Im1vY2stZzUwcXQxajgiLCJwdWJsaWMudG90YWwiOiI0MS44MiIsInB1YmxpYy5kb25hdGlvbl9hbW91bnQiOiI0MC4wMCIsInB1YmxpYy5mZWUiOiIxLjgyIiwicHVibGljLmN1cnJlbmN5X3N5bWJvbCI6IiQifSwib25fYmVoYWxmX29mIjpudWxsLCJvcmRlciI6bnVsbCwib3V0Y29tZSI6eyJuZXR3b3JrX3N0YXR1cyI6ImFwcHJvdmVkX2J5X25ldHdvcmsiLCJyZWFzb24iOm51bGwsInJpc2tfbGV2ZWwiOiJub3JtYWwiLCJzZWxsZXJfbWVzc2FnZSI6IlBheW1lbnQgY29tcGxldGUuIiwidHlwZSI6ImF1dGhvcml6ZWQifSwicGFpZCI6dHJ1ZSwicmVjZWlwdF9lbWFpbCI6bnVsbCwicmVjZWlwdF9udW1iZXIiOm51bGwsInJlZnVuZGVkIjpmYWxzZSwicmVmdW5kcyI6eyJvYmplY3QiOiJsaXN0IiwiZGF0YSI6W10sImhhc19tb3JlIjpmYWxzZSwidG90YWxfY291bnQiOjAsInVybCI6Ii92MS9jaGFyZ2VzL2NoXzFCc3U1QkM1S3pFekhQTmhSNlUwVm5FVC9yZWZ1bmRzIn0sInJldmlldyI6bnVsbCwic2hpcHBpbmciOm51bGwsInNvdXJjZSI6eyJpZCI6ImNhcmRfMUJzc3JWQzVLekV6SFBOaFZ4SmFCaGJXIiwib2JqZWN0IjoiY2FyZCIsImFkZHJlc3NfY2l0eSI6bnVsbCwiYWRkcmVzc19jb3VudHJ5IjpudWxsLCJhZGRyZXNzX2xpbmUxIjpudWxsLCJhZGRyZXNzX2xpbmUxX2NoZWNrIjpudWxsLCJhZGRyZXNzX2xpbmUyIjpudWxsLCJhZGRyZXNzX3N0YXRlIjpudWxsLCJhZGRyZXNzX3ppcCI6bnVsbCwiYWRkcmVzc196aXBfY2hlY2siOm51bGwsImJyYW5kIjoiVmlzYSIsImNvdW50cnkiOiJVUyIsImN1c3RvbWVyIjoiY3VzX0NIUmxPWXI1d3JkeG96IiwiY3ZjX2NoZWNrIjpudWxsLCJkeW5hbWljX2xhc3Q0IjpudWxsLCJleHBfbW9udGgiOjEyLCJleHBfeWVhciI6MjAyMiwiZmluZ2VycHJpbnQiOiI4eURYczc4STFtTE8yeldKIiwiZnVuZGluZyI6ImNyZWRpdCIsImxhc3Q0IjoiNDI0MiIsIm1ldGFkYXRhIjp7fSwibmFtZSI6bnVsbCwidG9rZW5pemF0aW9uX21ldGhvZCI6bnVsbH0sInNvdXJjZV90cmFuc2ZlciI6bnVsbCwic3RhdGVtZW50X2Rlc2NyaXB0b3IiOm51bGwsInN0YXR1cyI6InN1Y2NlZWRlZCIsInRyYW5zZmVyX2dyb3VwIjpudWxsfSwidXNlcklkIjoxNCwiZ3N0IjowLCJjYW1wYWlnblV1aWQiOiI0N2E4MThjMC0wYjJlLTExZTgtOWUzNC1jZjc1NDUzNDI4YWMiLCJ1c2VyVXVpZCI6ImEzZmE5NjcwLTBiMmUtMTFlOC1hM2JjLTIzMGE3MjNhODBhYiIsInVzZXIiOnsidXVpZCI6ImEzZmE5NjcwLTBiMmUtMTFlOC1hM2JjLTIzMGE3MjNhODBhYiIsImNyZWF0ZWRBdCI6IjIwMTgtMDItMDZUMTE6MTI6MzguMjM1WiIsInVwZGF0ZWRBdCI6IjIwMTgtMDItMDZUMTE6MTI6MzguMjM1WiIsImZhY2Vib29rSWQiOm51bGwsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInVzZXJuYW1lIjoidGVzdEB0ZXN0LmNvbSIsInBlcm1pc3Npb24iOiJQQVJUSUNJUEFOVCIsImFkZHJlc3MxIjpudWxsLCJhZGRyZXNzMiI6bnVsbCwicG9zdGNvZGUiOm51bGwsInN0YXRlIjpudWxsLCJzdWJ1cmIiOm51bGwsImNvdW50cnkiOm51bGwsImludGVybmFsIjp7fSwicHVibGljIjpudWxsLCJwcml2YXRlIjpudWxsLCJmaXJzdE5hbWUiOiJUZXN0IiwibGFzdE5hbWUiOiJUZXN0IiwicGhvdG9VcmwiOm51bGwsInBob25lTnVtYmVyIjpudWxsLCJpcE51bWJlciI6bnVsbCwiaXBMYXRpdHVkZSI6bnVsbCwiaXBMb25naXR1ZGUiOm51bGwsImlwQ2l0eSI6bnVsbCwiaXBDb3VudHJ5IjpudWxsfSwiZmlyc3ROYW1lIjoiVGVzdCIsImxhc3ROYW1lIjoiVGVzdCIsImNhbXBhaWduRmVlIjowLCJjYW1wYWlnbkFtb3VudCI6MCwicHJvdmlkZXJSYWlzZWx5IjowLCJjYXJkUHJldmlldyI6NDI0MiwiZmVlT3B0SW4iOnRydWUsInB1YmxpY0Ftb3VudCI6NDAsInB1YmxpY0ZlZSI6MS44MiwicHVibGljVG90YWwiOm51bGx9LCJsZWdhY3lQYXlsb2FkIjpudWxsfQ==",
    "excludeFromIndexes": true
  }
]
```

Using this code which is running on Cloud Functions:
```
  const key = datastore.key(['Event']);
  await datastore.save({
    key,
    data: entity
  });
```

I started with the shorthand format of `{key, data, excludeFromIndexes: []}`, I've converted the JSON to a string and now base64 encoded it here in the example.

I'm consistently getting this error:
`"Error: The value of property "data" is longer than 1500 bytes.
    at /user_code/node_modules/@google-cloud/datastore/node_modules/grpc/src/client.js:554:15"  `

While I know the index limits, shouldn't that base64 blob be excluded from indexes and therefore be allowed if it's under 1mb?

Any ideas would be great, I'm stumped. Thanks so much

### Edit
I've just noticed that these entities are actually being saved in datastore *most* of the time, despite the error message.
![image](https://user-images.githubusercontent.com/3466825/35922818-adaa5b02-0c72-11e8-9490-0367ea665ae6.png)

One has been dropped due to a different error, in case it's helpful:
`"Error: Endpoint read failed
    at /user_code/node_modules/@google-cloud/datastore/node_modules/grpc/src/client.js:554:15"  `

#### Environment details

  - OS: Cloud Functions
  - Node.js version: 6
  - npm version: 5
  - @google-cloud/datastore version: 1.1.0

**Comment by tommaitland** [comment]
Oh dear, this might be my most embarrassing issue opened 😳. No bugs in the library, for anyone else who ends up in the same situation I had an `update` call further down the function and it didn't exclude indexes.

Lesson learnt, exclude indexes everywhere!
