### ISSUE TITLE
Error on Mocha JSON request with firebase.

### ISSUE THREAD

**Issue by RFlintstone** [googleapis/nodejs-datastore#594]
Hi Firebase Team, 

I'm trying to make my own test with [mocha](https://mochajs.org) but I don't seem to get mocha work with firebase's express module. 
I followed the documentation and multiple videos however I can't seem to let it work. I'm trying to call a json file (with content) and check if it has specific content in it.

My code:
```
var request = require('supertest');
var app = require('../index');

describe("Read Request", function () {
    it('should request a json file that has items in it.', function (done) {
        request(app).get("/project_name/europe-west1/task/read")
            .expect(200)
            .expect(`"created_at"`)
            // .expect("name")
            // .expect("description")
            // .expect("price")
    });
});
```

Output:
```
  1) Read Request
       should request a json file that has items in it.:
     TypeError: app.address is not a function
      at Test.serverAddress (node_modules\supertest\lib\test.js:55:18)
      at new Test (node_modules\supertest\lib\test.js:36:12)
      at Object.obj.(anonymous function) [as get] (node_modules\supertest\index.js:25:14)
      at Context.<anonymous> (test\test.js:6:22)
```

The data that is in the json file is directly outputted by Google Datastore.

**Comment by RFlintstone** [comment]
**Update:**

I exported the module:
```
    router = exports.task = functions.region(region).https.onRequest(app);
    module.exports = router;
```
And changed the test to:
```
var request = require('supertest');
var router = require('../index');

describe("Read Request", function () {
    it('should request a json file that has items in it.', function (done) {
        request(router).get("/kynda-lab/europe-west1/task/read/")
            .expect(200)
            .expect(/created_at/)
            .expect(/name/)
            .expect(/description/)
            .expect(/price/, done);
    });
});
```
The test now completly works!

**Comment by bcoe** [comment]
:wave:  @RFlintstone sounds like things are sorted out :+1: 

Let us know if you continue bumping in to any issues.
