### ISSUE TITLE
Invalid JWT causes hang on unrejected promise

### ISSUE THREAD

**Issue by kevinohara80** [googleapis/nodejs-datastore#94]
We started noticing that we were getting request timeouts to an api we created that was calling cloud datastore from node.js. Upon further inspection, it appears that the test JWT we were using was invalid. The problem here is that when a cloud datastore call is made with an invalid JWT, the Promise returned from the call is never rejected causing our application to hang. Also, in the console, there seems to be a loop of log statements that read `Auth error:Error: invalid_grant: Invalid JWT Signature`. Eventually, there seems to be some internal `gax` timeout but the return promise is still not rejected.

#### Environment details

  - OS: (Multiple) Mac OSX / Alpine Linux / Ubuntu Linux
  - Node.js version: 8.11.1
  - npm version: 5.8.0
  - `@google-cloud/datastore` version: 1.4.0

#### Steps to reproduce

  1. Try example code below with an invalid JWT
  2. Examine console logs and lack of promise rejection

#### Example code

Here is a snippet of the code. This shows the datastore constructor and the express request handler we have implemented

```js
const datastore = new Datastore({
  keyFilename: PATH_TO_INVALID_KEY_FILE
});

app.get('/', async (req, res, next) => {

  try {

    let query, keyOnlyQuery, result, keyOnlyResult;

    query = datastore
      .createQuery('testnamespace', 'testkind')
      .order('created_at')
      .limit(20);

    keyOnlyQuery = datastore
      .createQuery('testnamespace', 'testkind')
      .select('__key__')

    const promises = []
    
    promises.push(query.run());
    promises.push(keyOnlyQuery.run())

    [result, keyOnlyResult] = await Promise.all(promises)

    res.status(200).json({
      status: 'success'
    })
    
  } catch (err) {
    console.log('YOU SHOULD SEE THIS IF ONE OF THE PROMISES GETS REJECTED');
    return res.status(500).json({ message: err.message })
  }
  
});
```

#### Resulting Logs

```bash
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Auth error:Error: invalid_grant: Invalid JWT Signature.
Error: Retry total timeout exceeded before anyresponse was received
    at repeat (/Users/kohara/dev/bw/kipi-contacts-service/node_modules/google-gax/lib/api_callable.js:223:11)
    at Timeout._onTimeout (/Users/kohara/dev/bw/kipi-contacts-service/node_modules/google-gax/lib/api_callable.js:265:13)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
Error: Retry total timeout exceeded before anyresponse was received
    at repeat (/Users/kohara/dev/bw/kipi-contacts-service/node_modules/google-gax/lib/api_callable.js:223:11)
    at Timeout._onTimeout (/Users/kohara/dev/bw/kipi-contacts-service/node_modules/google-gax/lib/api_callable.js:265:13)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/gax-nodejs#252
